/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RoastChain {
  export type RoastStruct = {
    id: BigNumberish;
    author: AddressLike;
    content: string;
    votes: BigNumberish;
    timestamp: BigNumberish;
  };

  export type RoastStructOutput = [
    id: bigint,
    author: string,
    content: string,
    votes: bigint,
    timestamp: bigint
  ] & {
    id: bigint;
    author: string;
    content: string;
    votes: bigint;
    timestamp: bigint;
  };
}

export interface RoastChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllRoasts"
      | "getRoastsByAuthor"
      | "hasVoted"
      | "roasts"
      | "submitRoast"
      | "vote"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RoastSubmitted" | "Voted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllRoasts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoastsByAuthor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roasts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "submitRoast", values: [string]): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "getAllRoasts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoastsByAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roasts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRoast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace RoastSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    author: AddressLike,
    content: string
  ];
  export type OutputTuple = [id: bigint, author: string, content: string];
  export interface OutputObject {
    id: bigint;
    author: string;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    id: BigNumberish,
    voter: AddressLike,
    newVoteCount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, voter: string, newVoteCount: bigint];
  export interface OutputObject {
    id: bigint;
    voter: string;
    newVoteCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoastChain extends BaseContract {
  connect(runner?: ContractRunner | null): RoastChain;
  waitForDeployment(): Promise<this>;

  interface: RoastChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllRoasts: TypedContractMethod<
    [],
    [RoastChain.RoastStructOutput[]],
    "view"
  >;

  getRoastsByAuthor: TypedContractMethod<
    [_author: AddressLike],
    [RoastChain.RoastStructOutput[]],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  roasts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        id: bigint;
        author: string;
        content: string;
        votes: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  submitRoast: TypedContractMethod<[_content: string], [void], "nonpayable">;

  vote: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllRoasts"
  ): TypedContractMethod<[], [RoastChain.RoastStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRoastsByAuthor"
  ): TypedContractMethod<
    [_author: AddressLike],
    [RoastChain.RoastStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "roasts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        id: bigint;
        author: string;
        content: string;
        votes: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitRoast"
  ): TypedContractMethod<[_content: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "RoastSubmitted"
  ): TypedContractEvent<
    RoastSubmittedEvent.InputTuple,
    RoastSubmittedEvent.OutputTuple,
    RoastSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "RoastSubmitted(uint256,address,string)": TypedContractEvent<
      RoastSubmittedEvent.InputTuple,
      RoastSubmittedEvent.OutputTuple,
      RoastSubmittedEvent.OutputObject
    >;
    RoastSubmitted: TypedContractEvent<
      RoastSubmittedEvent.InputTuple,
      RoastSubmittedEvent.OutputTuple,
      RoastSubmittedEvent.OutputObject
    >;

    "Voted(uint256,address,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
